.TH WIKKID-SERVE "1" "January 2011" "wikkid-serve 0.2dev" "User Commands"
.SH NAME
wikkid-serve \- Serve a wiki from a Bazaar branch
.SH SYNOPSIS
.B wikkid-serve
[\fIoptions\fR] \fI<wiki-branch>\fR
.SH DESCRIPTION
Run a stand-alone Wikkid Wiki server.
.SH OPTIONS
.TP
\fB\-\-version\fR
show program's version number and exit
.TP
\fB\-h\fR, \fB\-\-help\fR
show this help message and exit
.TP
\fB\-\-host\fR=\fIHOST\fR
The interface to listen on. Defaults to 'localhost'
.TP
\fB\-\-port\fR=\fIPORT\fR
The port to listen on.  Defaults to 8080.
.TP
\fB\-\-default\-format\fR=\fIDEFAULT_FORMAT\fR
Specify the default wiki format to use. Defaults to
\&'rest'
.SH "LICENSE"
Wikkid is licensed under the
.B GNU Affero General Public License
.SH "SEE ALSO"
The wikkid home page can be found at
.B https://launchpad.net/wikkid
